### ISSUE TITLE
Problem running "imap/Negotiation/L_1_A.ron"

### ISSUE THREAD

**Issue by bloppydrago** [FHMS-ITS/EAST#4]
Hi i've no experience in rust and there seems to be an issue with the override_login, tag: ... When I run it there is an error saying Expected struct. I am doing something wrongly?

<img width="730" alt="Screenshot 2021-09-20 102608" src="https://user-images.githubusercontent.com/91040389/133952249-f3cc65a5-93a9-482d-9c02-1eae9d1b5634.png">

**Comment by duesee** [comment]
Hey @bloppydrago,

You did nothing wrong, the file contained an error. I fixed it here: https://github.com/Email-Analysis-Toolkit/fake-mail-server/commit/daef6da1844f5126417f5f7e8d6d16268dae0053.

Generally, the configuration format is not great now, because it exposes all low-level details of [imap-codec](https://github.com/duesee/imap-codec#example-binary), which is the IMAP library we used.

As you can see here

https://github.com/duesee/imap-codec/blob/0a4972ba9898a3b76b83f0684487289d1023dfb1/src/types/response.rs#L76 

, IMAP tags in imap-codec are wrapped in a `Tag` struct, hence the `Expected struct` error.

This wrapping is used in imap-codec to make IMAP tags type-safe, but makes less sense in the Fake Mail Server. Unfortunately, this is what we have for now.

---

If you want to further experiment with the server:

All options are defined here

https://github.com/Email-Analysis-Toolkit/fake-mail-server/blob/main/src/imap/config.rs#L39

and the ron file format is generally very "close" to Rust syntax. Thus, you should get pretty far by skipping through the config.ron and imap-codec source.

However, it may be easier to just use the

```
override_response: {
    "login": "<tag> Hello, bloppydrago!\r\n",
},
```

option. The downside is, that you need to take care about the syntax such as to not introduce syntactically invalid IMAP responses. We know from experience that this happens pretty fast. (Thus the "type-safe" imap-codec library :-)) Don't forget to finish the responses with "\r\n"!

If you have a specific IMAP string you want to test, e.g. something completely weird, and are not sure if it is syntactically correct, you could also try [the examples in imap-codec](https://github.com/duesee/imap-codec#example-binary) to test the response first.

Thank you for the issue, btw!

**Comment by bloppydrago** [comment]
@duesee thanks so much for the solution. It works now :)
